### ISSUE TITLE
[SWADE] It's not working with skills

### ISSUE THREAD

**Issue by brunocalado** [kandashi/Active-Auras#189]
**Describe the bug**
Allies in range don't get the fighting +1.
![image](https://user-images.githubusercontent.com/4999783/136217501-290775d4-125b-4b49-a4a2-0448a3567464.png)

**To Reproduce**
1. Add the effect: @Skill{Fighting}[data.die.modifier] add 1
2. Test allies in range

**Environment:**
win10
chrome
fvtt 8.9
swade 21

**Comment by kandashi** [comment]
Does that effect work if you dont apply it through AA ?

**Comment by kandashi** [comment]
Are the allies actually recieving the effects?

**Comment by Deadlander** [comment]
I can verify the issue.  However, in addition to not adding the skill bonus, it also isn't adding anything else. Video for visuals:

https://user-images.githubusercontent.com/13036735/152165511-ac24ff80-e8e4-4abb-a924-46077f6de3cf.mp4

**Comment by SalieriC** [comment]
I'm also unable to get it to work (no other modules active) on SWADE. :-S

**Comment by bloy** [comment]
I noticed this issue and went to verify for myself, it appears to be fixed in the current version. 
![image](https://github.com/kandashi/Active-Auras/assets/1473405/08a0bba3-971d-4b5f-95bb-385ed59b1cd5)
![image](https://github.com/kandashi/Active-Auras/assets/1473405/50eedf87-f9c8-485c-92c3-f139ff8c806c)
![image](https://github.com/kandashi/Active-Auras/assets/1473405/397071e3-8ff0-45eb-8685-931bd4bcb850)
![image](https://github.com/kandashi/Active-Auras/assets/1473405/b3c488c6-0a2e-4961-8461-60726bf30642)

I can't remember when it was but obviously `data` was deprecated in favor of `system` in foundry v10 or v11.

**Comment by MrPrimate** [comment]
Yes, this is probably fixed some changes were made a while ago to improve SWADE compatibility.
